import { describe, it, expect } from 'vitest';
import { detectModel } from '../src/detector/model.js';

describe('detectModel', () => {
  it('detects Claude from ANTHROPIC_API_KEY', () => {
    const result = detectModel({ ANTHROPIC_API_KEY: 'sk-test' });
    expect(result.model).toBe('claude');
    expect(result.source).toBe('env');
  });

  it('detects GPT from OPENAI_API_KEY', () => {
    const result = detectModel({ OPENAI_API_KEY: 'sk-test' });
    expect(result.model).toBe('gpt');
  });

  it('detects Gemini from GOOGLE_API_KEY', () => {
    const result = detectModel({ GOOGLE_API_KEY: 'test' });
    expect(result.model).toBe('gemini');
  });

  it('returns null when no env vars set', () => {
    const result = detectModel({});
    expect(result.model).toBeNull();
    expect(result.confidence).toBe(0);
  });

  it('detects model from commit trailer', () => {
    const result = detectModel({}, 'feat: add login\n\nAI-Model: claude');
    expect(result.model).toBe('claude');
    expect(result.source).toBe('commit-trailer');
    expect(result.confidence).toBe(1.0);
  });

  it('detects model from commit message mention', () => {
    const result = detectModel({}, 'Generated by copilot');
    expect(result.model).toBe('copilot');
    expect(result.source).toBe('commit-message');
  });

  it('prefers commit trailer over env', () => {
    const result = detectModel({ OPENAI_API_KEY: 'sk-test' }, 'AI-Model: claude');
    expect(result.model).toBe('claude');
    expect(result.source).toBe('commit-trailer');
  });
});
