export interface PRCommentData {
  files: Array<{
    path: string;
    aiGeneratedPct: number;
    reviewDepth: 'none' | 'reviewed' | 'tested' | 'verified';
    linesChanged: number;
  }>;
  totalFiles: number;
  avgAiPct: number;
  commitHash: string;
}

export function renderPRComment(data: PRCommentData): string {
  const lines: string[] = [
    '## 🔍 Agent Provenance Report',
    '',
    `**Commit:** \`${data.commitHash.slice(0, 8)}\``,
    `**Files analyzed:** ${data.totalFiles}`,
    `**Avg AI-generated:** ${data.avgAiPct}%`,
    '',
  ];

  if (data.files.length > 0) {
    lines.push(
      '| File | AI % | Review Depth | Lines Changed |',
      '|------|------|-------------|---------------|',
    );

    for (const f of data.files) {
      const icon = f.aiGeneratedPct > 70 ? '🤖' : f.aiGeneratedPct > 30 ? '🔶' : '👤';
      const reviewIcon = f.reviewDepth === 'none' ? '⚠️' : f.reviewDepth === 'verified' ? '✅' : '📝';
      lines.push(`| ${icon} ${f.path} | ${f.aiGeneratedPct}% | ${reviewIcon} ${f.reviewDepth} | ${f.linesChanged} |`);
    }
  } else {
    lines.push('No supported source files found in this PR.');
  }

  lines.push(
    '',
    '---',
    '<sub>Generated by <a href="https://github.com/phoenix-assistant/agent-prov">agent-prov</a></sub>',
  );

  return lines.join('\n');
}
